apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-learning-deployment
  labels:
    app: my-deployment
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - name: my-container
        image: urvish667/machine-learning:v1
