apiVersion: v1
kind: Service
metadata: 
  name: machine-learning-service
spec:
  ports:
  - nodePort: {{ .Values.port }}
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-deployment
  type: NodePort
